numbers={5,6,8,2,0}
print(numbers)
numbers.add(7)
numbers.add(3)
numbers.add(5)
print(numbers)
numbers.remove(5)
print(numbers)
print(len(numbers))
print(5 in numbers)
print(9 in numbers)
print(8 in numbers)
print(7 not in numbers)
print(10 not in numbers)
