string=input("Enter any string :")
print(string.capitalize())
print(string.casefold())
print(string.count('a'))
print(string.isupper())
print(string.islower())
print(string.isalpha())
print(string.isascii())
print(string.isdecimal())
print(string.isdigit())
print(string.lower())
